config/routes.rb
Rails.application.routes.draw do
  get 'top/main'
  resources :users
  resources :tweets
  root 'top#main'
  
  get 'top/main'
  post 'top/login'
  get 'top/logout'
  
  resources :likes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :tweet
    belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    has_many :likes, dependent: :destroy
    has_many :like_users, through: :likes, source: :user
    def like(user)
        likes.create(user_id: user.id)
    end

    def unlike(user)
        likes.find_by(user_id: user.id).destroy
    end

    def liked?(user) #いいね済みか調べる(true / false)
        like_users.include?(user)
    end
    
end

app/models/user.rb
class User < ApplicationRecord
    has_many :likes, dependent: :destroy
    has_many :tweets, dependent: :destroy
    has_many :like_tweets, through: :likes, source: :tweet
    
    validates :password, presence: true, confirmation: true
    
    attr_accessor :password, :password_confirmation

    def password=(val)
        if val.present?
            self.pass = BCrypt::Password.create(val)
        end
        @password = val
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
        def current_user
            if session[:uid]
                User.find_by(uid: session[:uid])
            end
        end
        helper_method :current_user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        tweet = Tweet.find(params[:tweet_id])
        unless tweet.liked?(current_user)
            tweet.like(current_user)
        end
        redirect_to tweets_path
    end
    def destroy
        tweet = Tweet.find(params[:id])
        if tweet.liked?(current_user)
            tweet.unlike(current_user)
        end
        redirect_to tweets_path
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    if session[:uid]
      render 'main'
    else
      render 'login'
    end
  end
  
  def login
    user = User.find_by(uid: params[:uid])
    if user
      login_password = BCrypt::Password.new(user.pass)
      if login_password == params[:pass]
        session[:uid] = user.uid
        redirect_to top_main_path
      else
        render 'login'
      end
    else
      render 'login'
    end
  end
  
  def logout
    session.delete(:uid)
    redirect_to top_main_path
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end

  def new
    @tweets = Tweet.new
  end
  
  def create
    user = User.find_by(uid: session[:uid])
    tweet = Tweet.new(message: params[:tweet][:message], tdate: Time.current, user_id: user.id)
    if tweet.save
      redirect_to tweets_path
    else
      render new_tweet_path
    end
  end
  
  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to tweets_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @users = User.new
  end
  
  def create
    @user = User.new(uid: params[:user][:uid],password: params[:user][:password],password_confirmation: params[:user][:password_confirmation])
    if @user.save
      redirect_to users_path
    else
      render 'new'
    end
  end
  
  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kadai1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/login.html.erb
<%= link_to 'ツイートページ', tweets_path %><br>
<%= link_to 'ユーザー新規登録', users_path %><br>
<%= form_tag '/top/login', method: :post do %>
    <%= label_tag :uid, 'ユーザーID' %>
    <%= text_field_tag :uid %>
    <%= label_tag :pass, 'パスワード' %>
    <%= password_field_tag :pass %>
    <%= submit_tag '登録' %>
<% end %>

app/views/top/main.html.erb
<%= link_to 'ツイート', tweets_path %><br>
<%= link_to 'ログアウト', top_logout_path %>

app/views/tweets/index.html.erb
<% @tweets.each do |e| %>
    <p>    
        <%= e.message %>
        <%= (Time.current - e.tdate).to_i / 60 %>分前
        <%= link_to '削除', tweet_path(e.id), method: :delete %>
        
        <% if session[:uid] %>
            <% if e.likes.count == 0 %>
                <%= link_to '♡', likes_path(tweet_id: e.id), method: :post %>
            <% else %>
                <%= link_to '♥', like_path(e), method: :delete %>
            <% end %>
        <% end %>
    </p>
<% end %>

<% if session[:uid] %>
    <%= link_to '新規追加', new_tweet_path %>
<% else %>
    <%= link_to 'ログイン', top_main_path %>
<% end %>
<br><%= link_to '戻る', top_main_path %>

app/views/tweets/new.html.erb
<%= form_for @tweets, action: :create do |f| %>
    <%= f.label :message, 'メッセージ'  %>
    <%= f.text_field :message %>
    <%= f.submit 'ツイート' %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |e| %>
    <p>    
        <%= e.uid %>
        <%= e.pass %>
        <%= link_to '削除', user_path(e.id), method: :delete %>
    </p>
<% end %>

<%= link_to '新規追加', new_user_path %><br>
<%= link_to 'ログイン', root_path %>

app/views/users/new.html.erb
<%= form_for @users, action: :create do |f| %>
    <%= f.label :uid, 'UID'  %>
    <%= f.text_field :uid %>
    <%= f.label :password, 'PASS'  %>
    <%= f.text_field :password %>
    <%= f.label :password_confirmation, 'PASS(確認)' %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit '登録' %>
<% end %>